# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - petstore/petstorepetservice/*

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '2f7c9697-f237-4d5b-994d-4228eed03f32'
  imageRepository: 'petstorepetservice'
  containerRegistry: 'azurepetstorecr.azurecr.io'
  dockerfilePath: 'petstore/petstorepetservice/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: '$(crImagePullSecretGlobal)'

stages:
- stage: Build
  displayName: Build stage
  jobs: 
  - job: Analysis
    displayName: Security Analysis
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: CredScan@2
      inputs:
        toolMajorVersion: 'V2'
 
  - job: Build
    displayName: Build App
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo -n -e "{\"version\":\"$(Build.BuildNumber) - $(tag)\"}" > petstore/petstorepetservice/src/main/resources/version.json

    - task: Maven@3
      continueOnError: true 
      displayName: Build Spring Boot Jar
      inputs:
        mavenPomFile: 'petstore/petstorepetservice/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: 'petstore/petstorepetservice/target/surefire-reports/TEST-*.xml'
        codeCoverageToolOption: 'jaCoCo'
        goals: 'package'
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
          
    - upload: manifests
      artifact: manifests

- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy App
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create secret
            inputs: 
              action: createSecret
              kubernetesServiceConnection: azurepetstoreservices-akscluster-ingress-petstoreservices
              namespace: default
              secretType: dockerRegistry
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: azurepetstoreservices-akscluster-ingress-petstoreservices
              manifests: |
                $(Pipeline.Workspace)/manifests/petstorepetservice-deployment-everything-enabled.yml
                $(Pipeline.Workspace)/manifests/petstorepetservice-service-everything-enabled.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
                
- stage: Automation
  displayName: Automation stage
  jobs: 
  - job: Automation
    displayName: Automation Testing
    pool:
      vmImage: 'windows-latest'
    steps:
        - task: TriggerPipeline@1
          inputs:
            serviceConnection: 'Automation'
            project: '6b3206dd-90b3-40f6-a611-e5a1e5a13593'
            Pipeline: 'Build'
            buildDefinition: 'azure-petstoreautomation-regression-tests'
            Branch: 'main'
